import maths.factorial;
// Imports factorial generated by Ralang

public class test {
    public static void main(String[] args) {
        System.out.println(factorial.factorial(1));
        System.out.println(factorial.factorial(3));
        System.out.println(factorial.factorial(5));
        System.out.println(factorial.factorial(7));
        System.out.println(factorial.factorial(9));
    }
}